### ISSUE TITLE
Animation with <transition>

### ISSUE THREAD

**Issue by VladStepanov** [euvl/vue-notification#143]
Because of in nuxt haven't default css layout, i have to use custom, but that doesn't work properly
```
<transition name='fade'>
  <notification group='cart'>
    <template slot='body' props='props>
    </template>
  </notification>
</transition>
```
I need any animation, even default

**Comment by smitpatelx** [comment]
@VladStepanov @euvl 
I added animation in CSS like this. But I couldn't figure out a way to leaving animation.

> **If someone finds out please let us know.**

```scss
@keyframes slide-left{0%{transform:translateX(0px)}100%{transform:translateX(-50px)}}

//Then add this animation to default class like this.
.vue-notification {
    animation:slide-left .5s cubic-bezier(.25,.46,.45,.94) forwards;
}
```
