### ISSUE TITLE
Can z-index not be hardcoded ?

### ISSUE THREAD

**Issue by wdpm** [euvl/vue-notification#205]
https://github.com/euvl/vue-notification/blob/ec256ad454a850b1dd404b1aca7d4b860392dded/src/Notifications.vue#L384
```css
.vue-notification-group {
  z-index: 5000;
}
```
Sometimes maybe I have a larger z-index(for example 9999) of the dialog layer than vue-notification-group
